### ISSUE TITLE
NPE After Upgrading from 0.61 to 0.62

### ISSUE THREAD

**Issue by codylerum** [DataDog/dd-trace-java#1874] opened 2020-09-16 14:02 UTC
```
java.lang.NullPointerException: Cannot invoke "com.timgroup.statsd.StatsDClient.count(String, long, String[])" because "this.statsd" is null
    at datadog.trace.agent.core.monitor.Counter.incrementErrorCount(Counter.java:30)
    at datadog.trace.agent.common.writer.ddagent.DDAgentApi.sendSerializedTraces(DDAgentApi.java:165)
    at datadog.trace.agent.common.writer.ddagent.PayloadDispatcher.accept(PayloadDispatcher.java:83)
    at datadog.trace.agent.core.serialization.msgpack.Packer.flush(Packer.java:152)
    at datadog.trace.agent.common.writer.ddagent.PayloadDispatcher.flush(PayloadDispatcher.java:34)
    at datadog.trace.agent.common.writer.ddagent.TraceProcessingWorker$TraceSerializingHandler.flushIfNecessary(TraceProcessingWorker.java:225)
    at datadog.trace.agent.common.writer.ddagent.TraceProcessingWorker$TraceSerializingHandler.runDutyCycle(TraceProcessingWorker.java:197)
    at datadog.trace.agent.common.writer.ddagent.TraceProcessingWorker$TraceSerializingHandler.run(TraceProcessingWorker.java:184)
    at java.lang.Thread.run(Thread.java:832)
SDK
```

**Comment by richardstartin** [comment] 2020-09-16 14:07
Hi @codylerum #1872 should fix this - a patch will be released soon. Sorry for the inconvenience and thanks for the report.

**Comment by flavium31** [comment] 2020-09-22 16:06
I'm getting this stack trace (Spring Boot application, JDK 11)

`Exception in thread "dd-trace-processor" java.lang.NullPointerException
	at datadog.trace.agent.core.monitor.Counter.incrementErrorCount(Counter.java:30)
	at datadog.trace.agent.common.writer.ddagent.DDAgentApi.sendSerializedTraces(DDAgentApi.java:165)
	at datadog.trace.agent.common.writer.ddagent.PayloadDispatcher.accept(PayloadDispatcher.java:83)
	at datadog.trace.agent.core.serialization.msgpack.Packer.flush(Packer.java:152)
	at datadog.trace.agent.common.writer.ddagent.PayloadDispatcher.flush(PayloadDispatcher.java:34)
	at datadog.trace.agent.common.writer.ddagent.TraceProcessingWorker$TraceSerializingHandler.flushIfNecessary(TraceProcessingWorker.java:225)
	at datadog.trace.agent.common.writer.ddagent.TraceProcessingWorker$TraceSerializingHandler.runDutyCycle(TraceProcessingWorker.java:197)
	at datadog.trace.agent.common.writer.ddagent.TraceProcessingWorker$TraceSerializingHandler.run(TraceProcessingWorker.java:184)
	at java.base/java.lang.Thread.run(Thread.java:834)`

Is it caused by the same issue?

**Comment by richardstartin** [comment] 2020-09-22 16:33
@flavium31 yes it is - we are doing a release with a fix later today. Apologies for the inconvenience.

**Closed** 2020-09-22 17:23 UTC
