### ISSUE TITLE
Agent spawns non-daemon threads preventing JVM exit when returning from `main`

### ISSUE THREAD

**Issue by Daenyth** [DataDog/dd-trace-java#991] opened 2019-09-13 15:34 UTC
I'm observing an issue where my application doesn't exit when it returns from `main`.

When I use visualvm to debug, I see non-daemon threads referencing `DatadogClassLoader`

I'd prefer if the JVM exited when `main` returns.

![Screen Shot 2019-09-13 at 11 34 27 AM](https://user-images.githubusercontent.com/14644/64875160-7c097880-d61a-11e9-98b0-24601edd8fa6.png)

As a workaround right now I call `sys.exit()`, but it's not ideal

**Comment by tylerbenson** [comment] 2019-10-11 15:33
Thanks for the report.  It's odd because we have tests that explicitly check this... What version of the tracer are you running?  Any way you could provide more detailed explanation on how to reproduce the problem?

**Comment by Daenyth** [comment] 2019-10-11 18:26
We have 0.30.0 of the dd-java-agent jar deployed with our app, which is on heroku.

I notice the thread name from the heap dump above hints that it's from a generic thread factory that isn't naming its threads - so that rules out some of the possible options.

Could it be that something the agent is using is itself making this thread pool?

**Comment by tylerbenson** [comment] 2019-10-15 17:03
I guess it's possible, but I can't say for sure.  If you take a thread dump, does it show anything interesting being executed by the thread?

**Comment by tylerbenson** [comment] 2019-12-23 17:24
Any chance you could try and see if 0.40.0 fixes the problem?
Might be related to #1150.

**Comment by randomanderson** [comment] 2020-05-01 15:13
Closing this for now.  We've made numerous improvements to our thread handling: #1048, #1150, #1200, #1366 .  Please reopen if this is still an issue.

**Closed by randomanderson** 2020-05-01 15:13 UTC

**Comment by tylerbenson** [comment] 2020-05-04 13:55
May also be linked to #1422.
