### ISSUE TITLE
Is this package impacted by Log4j2 issue?

### ISSUE THREAD

**Issue by kubbafox** [DataDog/dd-trace-java#3265] opened 2021-12-14 14:10 UTC
I am using dd-trace-java in our server as Java APM. Is the package impacted by Log4j2 issue?

**Comment by mcculls** [comment] 2021-12-14 14:18
> No, log4j is not included. We have an integration for log4j that hooks into MDC but we do not bundle a version of log4j for that, we use the one that already included on the classpath if included at all

from https://github.com/DataDog/dd-trace-java/issues/3255

**Comment by mcculls** [comment] 2021-12-14 14:30
Closing as duplicate of #3255 - let us know if you need further details that aren't covered there

**Closed by mcculls** 2021-12-14 14:30 UTC
