### ISSUE TITLE
Jax RS Tracing broken

### ISSUE THREAD

**Issue by chouze** [DataDog/dd-trace-java#424] opened 2018-08-02 19:55 UTC
We upgraded our java agent to version `0.12.0` and noticed that we no longer received any traces for `servlet.request` in the Datadog APM dashboard. To the best of our knowledge we still received all the traces for all other types. We reverted back down to `0.11.0` and started receiving the `servlet.request` traces again. We are running jetty version `9.3.6.v20151106` and jersey version `2.22.1`.

**Comment by tylerbenson** [comment] 2018-08-03 05:36
Thanks for the report.  Would it be possible to open a support ticket so you can provide some logs and such?

**Comment by chouze** [comment] 2018-08-03 14:12
Opened ticket #160129 for this issue.

**Comment by chouze** [comment] 2018-08-13 14:59
Hello, sorry for the delay, I've sent in a few minutes of logs.

**Comment by tylerbenson** [comment] 2018-09-07 05:49
@chouze We've made a fair bit of changes since `0.12.0`.  I was wondering if you'd be willing to try again.  I don't have any particular reason to think we've fixed it, but I also don't know what is causing it, so I'm kinda hoping it's been unintentionally resolved.  This is the particular log line that is problematic:
```
[main] DEBUG datadog.trace.agent.tooling.AgentInstaller$LoggingListener - Failed to handle javax.servlet.http.HttpServlet for transformation on classloader sun.misc.Launcher$AppClassLoader@18b4aac2: Cannot resolve type description for javax.servlet.ServletRequest
```
Thanks!

**Comment by jrogers** [comment] 2018-09-11 01:17
Looks like this is working again in 0.14.0.

**Comment by chouze** [comment] 2018-09-17 14:51
Hi @tylerbenson, I just tried with `0.15.0~71059eac` It seems to be having the same issue as 0.12.0

**Comment by tylerbenson** [comment] 2018-09-17 21:45
@choze, darn. I was hopeful. Is it possible for you to provide a small sample app that reproduces the problem?

Can you tell me more about your application environment? Using Spring Boot, OSGi, or some other non-standard classloading setup?

**Comment by provDaveStimpert** [comment] 2019-02-27 15:01
from my experience, `servlet.request` is reported for spring boot services, but jersey services use a different format which is based on the class name and method name of the API endpoint.  Perhaps that is the point of confusion?

**Comment by randomanderson** [comment] 2019-10-24 16:18
Closing as abandoned.

We've made significant improvements to the tracer in the past year (and specifically Jax-rs more recently)

Please open a new issue if the problem persists with a newer version of the tracer.

**Closed by randomanderson** 2019-10-24 16:18 UTC
Labels: bug, needs-investigation
