### ISSUE TITLE
v1.6.0 is uploaded but not tagged properly in GCR

### ISSUE THREAD

**Issue by wujek-srujek** [DataDog/dd-trace-java#4658] opened 2023-02-04 08:06 UTC
Hi. The version v.1.6.0 is uploaded to GCR (can be verified by comparing image hashes) but the `v1.6.0` tag is missing. Compare:
https://console.cloud.google.com/gcr/images/datadoghq/GLOBAL/dd-lib-java-init
and
https://hub.docker.com/r/datadog/dd-lib-java-init/tags

This makes it impossible to use `v1.6.0` (`latest` still points to `v1.5.0 as well) with the default configuration pulling images from GCR.

**Comment by devinsba** [comment] 2023-02-04 17:30
Hi. Thanks for the report. We discovered this too and have already pushed a fix for the next release.

The problem is that the GitHub action we use to build the image updated the underlying tools even though we have the version of the action pinned. The new version of docker buildx produces manifests that GCR doesn't support.

**Comment by devinsba** [comment] 2023-02-07 15:23
I'm working on manually re-publishing the image to GCR this morning. Sorry for the inconvenience. I wasn't aware that the in app docs were using the version number for this release.

**Comment by devinsba** [comment] 2023-02-07 16:12
@wujek-srujek I've pushed the image to GCR now `Published successfully to: gcr.io/datadoghq/dd-lib-java-init:v1.6.0` please report back if you have an issue still

**Closed by devinsba** 2023-02-07 16:12 UTC

**Comment by wujek-srujek** [comment] 2023-02-08 08:54
1.6.0 is available and works fine, but now 1.7.0 is not tagged properly. Seems like you have an issue in your pipeline that uploads automatically, or something.

**Comment by wujek-srujek** [comment] 2023-02-08 16:28
Yeah the 1.7.0 tag is there now, but 8 hours ago when I commented it wasn't. All good now.
