### ISSUE TITLE
Traces not captured for webflux netty.request when request is canceled

### ISSUE THREAD

**Issue by deisenzimmer** [DataDog/dd-trace-java#3503] opened 2022-04-15 22:41 UTC
We use the Spring WebFlux project to develop Reactive Java API's.  Our API is called by an AWS load balancer having a 30 second timeout.  Traces work great under normal circumstances.  Some of our API's in turn call one or more API's hosted by partners.  When the partner is having latency issues, sometimes the load balancer times out and a cancel signal is propagated via reactive.  In that scenario traces are not sent to the trace agent and we are challenged in trying to detect and diagnose the timeouts.

I saw this issue which seems to be similar and is closed as fixed: https://github.com/DataDog/dd-trace-java/issues/1100

I am running version 0.99.0~c3bbd7bd60.

I enabled debugging, and under the normal scenario we have a pair of log entries show up for the root span like so:

[dd.trace 2022-04-15 14:30:44:817 -0500] [reactor-http-epoll-1] DEBUG datadog.trace.agent.core.DDSpan - Started span: DDSpan [ t_id=597002061400167561, s_id=5087710417904218129, p_id=0 ] trace=apitest/netty.request/netty.request metrics= tags={language=jvm, runtime-id=4a329753-dab8-4784-b73c-72400c7069e4, thread.id=32, thread.name=reactor-http-epoll-1}, duration_ns=0
[dd.trace 2022-04-15 14:30:48:294 -0500] [reactor-http-epoll-1] DEBUG datadog.trace.agent.core.DDSpan - Finished span (ROOT_BUFFERED): DDSpan [ t_id=597002061400167561, s_id=5087710417904218129, p_id=0 ] trace=apitest/netty.request/POST /v4/test metrics= *errored* *measured* tags={_dd.agent_psr=1.0, _sample_rate=1, component=netty, http.hostname=api.local.myfico.com, http.method=POST, http.route=/v4/test, http.status_code=500, http.url=http://api.local.myfico.com:30003/v4/test, language=jvm, peer.ipv4=192.168.65.3, peer.port=59924, runtime-id=4a329753-dab8-4784-b73c-72400c7069e4, span.kind=server, thread.id=32, thread.name=reactor-http-epoll-1}, duration_ns=3476727600

In the timeout scenario, we only have the start span log entry show up for the root span:
[dd.trace 2022-04-15 14:21:36:343 -0500] [reactor-http-epoll-3] DEBUG datadog.trace.agent.core.DDSpan - Started span: DDSpan [ t_id=6642874906945167855, s_id=3286022000880915977, p_id=0 ] trace=apitest/netty.request/netty.request metrics= tags={language=jvm, runtime-id=4a329753-dab8-4784-b73c-72400c7069e4, thread.id=39, thread.name=reactor-http-epoll-3}, duration_ns=0

We do get two odd log entries which I wonder if they are related:
[dd.trace 2022-04-15 14:21:37:659 -0500] [reactor-http-epoll-3] DEBUG datadog.trace.agent.tooling.Instrumenter$Default - Muzzled - instrumentation.names=[netty,netty-4.0] instrumentation.class=datadog.trace.instrumentation.netty40.ChannelFutureListenerInstrumentation instrumentation.target.classloader=jdk.internal.loader.ClassLoaders$AppClassLoader@9e89d68
[dd.trace 2022-04-15 14:21:37:659 -0500] [reactor-http-epoll-3] DEBUG datadog.trace.agent.tooling.Instrumenter$Default - Muzzled mismatch - instrumentation.names=[netty,netty-4.0] instrumentation.class=datadog.trace.instrumentation.netty40.ChannelFutureListenerInstrumentation instrumentation.target.classloader=jdk.internal.loader.ClassLoaders$AppClassLoader@9e89d68 muzzle.mismatch="datadog.trace.instrumentation.netty40.AttributeKeys:38 Missing method io.netty.util.AttributeKey#<init>(Ljava/lang/String;)V"

Is it possible to capture the traces correctly when the client times out and a reactive cancel signal is propagated?

**Comment by devinsba** [comment] 2022-04-18 21:02
What version of webflux are you on? It's possible this is an issue that re-emerged with changes to reactor and reactor-netty, or we never fully fixed it but parts of this instrumentation has been rewritten since the above PR

**Comment by devinsba** [comment] 2022-04-19 15:41
Yes, that mismatch would be expected since we have an alternate implementation for netty that covers 4.1+

Thanks for the version, that will help triage the issue

**Comment by howardem** [comment] 2023-09-19 19:59
Hi @devinsba we are running exactly into the same problem. All of our microservices are implemented using reactive Spring Boot / Webflux. When a client closes the connection due to some timeout connecting to Redis for example, we are able to see the reactor.netty.channel.AbortedException exception in the pod console, but those errors are never shown in Datadog. 

We are running containerized reactive Spring Boot 2.7.15 applications running on Java 17 (Eclipse Adoptium 17.0.8+7)

**Comment by howardem** [comment] 2023-09-19 22:33
Hi @deisenzimmer, were you able to figure out how to solve the mismatch issue with Datadog?

**Comment by deisenzimmer** [comment] 2023-09-20 13:30
Hi @howardem, we never did solve the mismatch issue nor the issue overall.  I think it's still occurring.

**Comment by howardem** [comment] 2023-09-20 16:52
Hi @deisenzimmer thanks for your response! Unfortunately the issue is still happening. We had it back when were using the same stack as you, reactive Spring Boot / Webflux 2.6.x, but even with Spring Boot 2.7.15 which relies on Netty 4.1.97 the problem hasn't been resolved by the Datadog folks.

**Comment by howardem** [comment] 2023-09-26 14:08
Hi @devinsba, it has been almost 4 years since this issue [No APM traces logged on canceled requests in Reactor](https://github.com/DataDog/dd-trace-java/issues/1100) was reported and it's still happening. Does Datadog Engineering Team have any plan or the **will** to solve this problem any time soon? A lot of development teams use WebFlux for their reactive Spring Boot microservices. And when it comes to Datadog, as exhibitor for the latest VMware Explore 2023 but also present in previous editions of Spring One Platform, in my honest opinion, Datadog, should've come up with solution long time ago.

This bug is a pressing issue for Engineering Teams using DD.

cc: @mcculls, @richardstartin, @bantonsson

**Comment by nabeelpaytrix** [comment] 2024-10-23 15:23
We have a similar issue in Spring Boot Webflux `2.7.18`

The current hypothesis is that Spring Boot is not Gracefully handling the Cancel signal received by the upstream client (in our case, this is an Istio sidecar which has configured a timeout).

I also heard from Datadog support that Datadog traces are propagated on the same thread which is responsible for handling the Span exports.

So a Cancel signal may be killing the thread which handles the rest of the Request, as well as the Datadog Span export, hence the missing Spans within the trace. We also notice that we don't see any more logs within this request, which suggests the thread has indeed been killed by the Cancel signal.

We have a workaround for this scenario, where we applied a Global OnCancel Webflux filter which flushes the pending Datadog Spans before terminating the thread:


```
import static org.springframework.http.HttpStatus.GATEWAY_TIMEOUT;

import java.time.Duration;

import io.opentracing.Span;
import io.opentracing.util.GlobalTracer;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.server.ServerWebExchange;
import org.springframework.web.server.WebFilter;
import org.springframework.web.server.WebFilterChain;
import reactor.core.publisher.Mono;

/**
 * Filter for handling timeout events.
 */
@Configuration
@Slf4j
public class GlobalTimeoutWebFilter implements WebFilter {

    @Override
    public Mono<Void> filter(final ServerWebExchange exchange, final WebFilterChain chain) {
        return chain.filter(exchange)
                .doOnCancel(() -> {
                    log.error("Client closed connection, likely due to timeout");
                    Span span = GlobalTracer.get().activeSpan();
                    if (span != null) {
                        span.log("Client closed connection");
                    }
                    exchange.getResponse().setStatusCode(GATEWAY_TIMEOUT);
                })
                // Ensure the span is finished after request completion (whether successful or timed out)
                .doFinally(signalType -> {
                    Span span = GlobalTracer.get().activeSpan();
                    if (span != null) {
                        span.finish();
                    }
                });
    }
}
```

**Closed** 2024-11-14 14:45 UTC
Labels: type: bug, inst: netty
