### ISSUE TITLE
Missing traces in Datadog APM with dd-java-agent:0.94.1 and spring-boot 2.6.3

### ISSUE THREAD

**Issue by franlr44** [DataDog/dd-trace-java#3435] opened 2022-03-10 11:56 UTC
Hello. 

In an existing java project we upgraded spring-boot from version `2.3.1.RELEASE` to `2.6.3` and also upgraded the dd-java-agent to 0.94.1 (using https://dtdg.co/latest-java-tracer ). Since then, we only see `repository.operation` traces in APM. Before that, everything worked well and we could see traces like `servlet.request` and `spring.handler` and we would really love them to be back.

Our Docker image is based on amazoncorretto:17.0.2 which should be supported from what is written [here](https://docs.datadoghq.com/tracing/setup_overview/setup/java/?tab=containers) 

Thank you.

**Comment by franlr44** [comment] 2022-03-10 15:06
Our APIs (those we want to monitor) are exposed with spring-webmvc but our outgoing calls use webflux.

**Comment by devinsba** [comment] 2022-03-10 16:09
Hmm, OK. I can't seem to reproduce. Can you take a look at the test app I just created. It's very basic. And maybe point me to differences? Perhaps you aren't using embedded tomcat, or are you building a war? Just those kinds of things would be good to know

**Comment by devinsba** [comment] 2022-03-10 16:14
I guess it helps if I actually post the URL that I copied to my clipboard: https://github.com/DataDog/dd-trace-java/pull/3437

**Comment by franlr44** [comment] 2022-03-18 15:58
Hello. To keep you up to date, our problem was that -Ddd.service={serviceName} was missing. So every traces were available in Datadog APM under the service named "root.servlet". Somehow it worked correctly before but not after the migration.
I guess you can close this issue. Thank you!

**Comment by devinsba** [comment] 2022-03-19 01:06
Thanks for the follow up. I'll close it but if you could answer a couple questions I'd appreciate it.

Were you using a different embedded servlet container before? Did you update the tracer at the same time as your spring-boot update?

I ask because I noticed some inconsistencies between our tomcat integration and the generic servlet on that could have caused this if you switched. And the second question is because there was a breaking change about 9 months ago that could have caused that as well.

**Closed** 2022-03-19 01:07 UTC
