### ISSUE TITLE
hikari connection pool reported as "unknown service"

### ISSUE THREAD

**Issue by n0mer** [DataDog/dd-trace-java#278] opened 2018-04-03 00:07 UTC
traces that belongs to hikari reported as "unknown" service

![image](https://user-images.githubusercontent.com/1862997/38222156-80dae60a-36e3-11e8-8c11-b61aa571ecb6.png)

Is there any way to configure datadog java agent for hikari connection pool, so service will be properly named?

**Comment by tylerbenson** [comment] 2018-04-04 03:41
Thanks for the report.  This is on our radar, we just haven't gotten around to hikari specific instrumentation to fix it yet.  Perhaps you'd be interested in submitting a PR?

**Comment by n0mer** [comment] 2018-04-11 23:51
@tylerbenson unfortunately, i'm neither python nor go dev

**Comment by tylerbenson** [comment] 2018-04-14 02:30
@n0mer I’m suggesting a PR to this repo, in java. Anyway, no worries. We will get around to it.

**Comment by n0mer** [comment] 2018-04-15 00:04
@tylerbenson  this one https://github.com/DataDog/dd-trace-java/pull/285 ? It is about java 7 & java 9 testing

**Comment by tylerbenson** [comment] 2018-05-08 06:32
With #314, Hikari should report as `database` instead of `uknown`, but you will also be able to rename the service name to what you like.

**Comment by n0mer** [comment] 2018-05-09 23:13
@tylerbenson can you please provide any detail on what exactly should i do in order to rename the service name?

**Comment by tylerbenson** [comment] 2018-05-10 04:09
@n0mer You'll want to add the following system properties (or corresponding environment variables):
* `dd.trace.rename.unknown` as `true`
* `dd.service.mapping` as `database:my-service postgres`

Where the mapping is defined as a comma delimited list of key value pairs, so customize as you see fit.
(Without the first setting, the name would be `unknown` instead of `database`.)

**Comment by n0mer** [comment] 2018-05-10 10:51
thanks @tylerbenson

**Comment by tylerbenson** [comment] 2018-05-18 03:27
I believe a combination of #314 and #322 should resolve this.  I'm going to close it.  Let me know if it needs to be reopened.

**Comment by n0mer** [comment] 2018-05-18 10:53
@tylerbenson this issue was raised not by devs, so it is questionable practice to close it w/out validation from reporter :) 

Anyway - can you please point to the relevant page at https://docs.datadoghq.com/ that explains how to supply service name of hikari connection pool to datadog agent? 

Thanks in advance.

**Comment by n0mer** [comment] 2018-05-18 10:57
so `-Ddd.trace.rename.unknown=true -Ddd.service.mapping=database:my-service mysql` should work? Space before `postgres` leads to `postgres` part being ignored

**Comment by tylerbenson** [comment] 2018-05-19 11:36
@n0mer I am guessing the space issue is a result over how it’s being interpreted by the shell. Can you try wrapping the mapping config part in quotes?

**Comment by gary-huang** [comment] 2018-05-19 17:44
@n0mer I believe that the issue with hikari connection pool being reported as an unknown service was because when the JDBC connection class throws an exception in its constructor, it leads to the actual name of the JDBC driver not being recorded as the service name after recovery, which in your case from your previous comments would be MySQL. #322 should've handled this. Along with configurations from #314, it should ensure that the proper service name is being recorded. Please let us know if you have more questions.

**Comment by tylerbenson** [comment] 2018-06-07 00:12
@n0mer please confirm that the issue is resolved, or let us know what the current problem is.

**Comment by n0mer** [comment] 2018-06-07 07:47
Tyler , if I understood correctly - the solution is to configure agent and
say that any unknown service should be reported as some placeholder name ,
right ?

**Comment by ctoestreich** [comment] 2018-06-20 15:25
This is also affect our APM using HikariCP as well.

![screen shot 2018-06-20 at 10 24 32 am](https://user-images.githubusercontent.com/691357/41668122-4276b6e0-7474-11e8-9d67-91ceafae6e73.png)

**Comment by tylerbenson** [comment] 2018-07-06 17:28
@n0mer is this ready to be closed out?

**Comment by ctoestreich** [comment] 2018-07-10 13:52
@tylerbenson  we put in 0.9.0 and this issue has been resolved.

**Closed** 2018-07-10 19:42 UTC
