### ISSUE TITLE
kafka-clients instrumentation doesn't work for all consumers

### ISSUE THREAD

**Issue by rgueldem** [DataDog/dd-trace-java#808] opened 2019-04-20 04:34 UTC
We use the [alpakka-kafka](https://github.com/akka/alpakka-kafka) client library which uses [`records​(TopicPartition partition)`]( https://kafka.apache.org/20/javadoc/org/apache/kafka/clients/consumer/ConsumerRecords.html#records-org.apache.kafka.common.TopicPartition-) for pulling consumers records. It seems that the kafka-clients instrumentation only covers `records​(String topic)`. This results in missing spans for our kafka consumers.

**Comment by gygabyte** [comment] 2019-07-06 20:58
same here.. any workaround available?

**Comment by mar-kolya** [comment] 2019-07-08 18:27
Hopfully #908 will help with this.

**Comment by gygabyte** [comment] 2019-07-09 21:16
@mar-kolya I have tested your change, but still the records(TopicPartition) is not being picked up by instrumentation. it is odd as it should be working... it should work by just building off master branch and use the dd-agent resulting from it?

**Comment by mar-kolya** [comment] 2019-07-09 21:22
@gygabyte yes, build from master should work. Would you be able to provide a simple example app that reproduces the problem?

**Comment by gygabyte** [comment] 2019-07-09 21:32
```
object Main extends App  {

  import scala.collection.JavaConverters._

  val s = new scala.collection.mutable.HashMap[String, Object]()
  s.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, classOf[StringDeserializer])
  s.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, classOf[StringDeserializer])
  s.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "127.0.0.1:9092")
  s.put(ConsumerConfig.GROUP_ID_CONFIG, "test-group")

  val c: KafkaConsumer[String, String] = new KafkaConsumer[String, String](s.asJava)

  val t = List("test-topic")

  c.subscribe(t.asJava)

  while(true) {
    val r = c.poll(java.time.Duration.of(100, java.time.temporal.ChronoUnit.MILLIS))
    val rs =
      r.records(new TopicPartition("test-topic", 0)).iterator()
    while (rs.hasNext) {
      val i = rs.next()
      System.out.println(i.value())
    }
  }
}
```
this code is written in Scala btw. it works if I switch to records(String)

**Comment by mar-kolya** [comment] 2019-07-10 15:45
@gygabyte could you please clarify what version of the kafka client are you using?

**Comment by gygabyte** [comment] 2019-07-10 16:02
@mar-kolya 2.1.1

**Comment by mar-kolya** [comment] 2019-07-10 17:49
@gygabyte could you please try #911

**Comment by mar-kolya** [comment] 2019-07-10 18:42
@gygabyte please scratch that, it won't work - but I think now I know why it won't work.

**Comment by gygabyte** [comment] 2019-07-10 20:31
I think I have figured out as well. It needs its own "ListAdvice" as the Iterable doesn't match the List<> type...

**Comment by mar-kolya** [comment] 2019-07-10 20:44
Yeah, and since it's a list fixing that is non trivial

**Comment by gygabyte** [comment] 2019-07-12 05:56
I have a solution to fix this one that I have tested. It involves a new advice. Working through some stuff (legal) at the moment, but I hope to be making a contribution soon

**Comment by mar-kolya** [comment] 2019-07-12 13:08
@gygabyte #911 has been updated and hopefully will be merged at some point

**Comment by gygabyte** [comment] 2019-07-12 17:55
I don't know.. seems to be breaking another instrumentation

**Comment by tylerbenson** [comment] 2019-07-25 23:32
This should be resolved in https://github.com/DataDog/dd-trace-java/releases/tag/v0.31.0

**Closed by tylerbenson** 2019-07-25 23:32 UTC
