### ISSUE TITLE
Duplicate spans created by @Trace annotation when public class inherits from package-private one

### ISSUE THREAD

**Issue by krosen040** [DataDog/dd-trace-java#4599] opened 2023-01-25 10:55 UTC
In the following situation

```java
import datadog.trace.api.Trace;

class A {
    @Trace
    public void foo() {
        return 42;
    }
}

public class B extends A {
}
```

Calls to `foo` will create two identical spans, one being the parent of the other. Any other combination of access modifiers seem to work as expected:

| | public B | package-private B |
|-- |------------- | ------------- |
| public A  | 1 span  | 1 span |
| package-private A  | 2 spans  | 1 span |

To verify this, remove the `public` modifier from [TracedSuperClass](https://github.com/DataDog/dd-trace-java/blob/v1.5.0/dd-java-agent/instrumentation/trace-annotation/src/test/java/dd/test/trace/annotation/TracedSuperClass.java#L5) and run the [tests](https://github.com/DataDog/dd-trace-java/blob/v1.5.0/dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsTest.groovy#L344), which will fail.

Tested on v1.5.0

**Comment by krosen040** [comment] 2023-01-25 11:19
```
$ java -version
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (Zulu 8.64.0.19-CA-macos-aarch64) (build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (Zulu 8.64.0.19-CA-macos-aarch64) (build 25.345-b01, mixed mode)
```

**Comment by mcculls** [comment] 2023-01-25 11:33
Thanks - I've tried old versions of the tracer and confirmed this behaviour has been around for a long time, so it's not a recent regression. We'll continue to look into why the synthetic method is not being ignored.

**Comment by mcculls** [comment] 2023-01-25 11:57
OK - found the root cause, the synthetic ignore at the method level is actually working as expected. The problem is in a different part of the trace annotation method matcher, which results in the original method having advice applied twice.

**Comment by mcculls** [comment] 2024-02-15 21:39
This will be fixed by switching to the simpler method graph in https://github.com/DataDog/dd-trace-java/pull/6579

**Closed** 2024-03-04 20:04 UTC
